includes: 
  - !include configs/main/common/DQNBase.yml

agent: NewModelAgent
model: NewModel
dueling-dqn: True
double-dqn: True

NM-lane-embedding-size: 32
NM-road-predict-hidden: 32
NM-scale-by-lane-number: True
NM-phase-loss-weight: 1
NM-volume-loss-weight: 1

num_nodes: 72
num_heads: 3
graph_hidden_dim: 64
graph_output_dim: 1
best_model: ./logs/best_model/best.pt